### PR TITLE
WIP: Add middleware support to the every validator

### PR DESCRIPTION
**Pull request by jeffhandley**
This illustrates what a middleware contract could look like for the `every` validator to support `reduceResults` and `prepareResult` middleware, that can wrap or override the default behavior of how results are aggregated.

The contract for middleware is:

``` js
const middleware = {
    reduceResults(nextReducer, accumulator, currentResult, { value, props, context }) {
        // This behaves as a passthrough middleware
        // The { value, props, context } argument will be provided automatically and it cannot be mutated
        return nextReducer(accumulator, currentResult);
    },
    prepareResult(nextPrepare, result, { value, props, context }) {
        // This behaves as a passthrough middleware
        // The { value, props, context } argument will be provided automatically and it cannot be mutated
        return nextPrepare(result);
    }
};
```

This `middleware` can be supplied:

1. As part of the validator props
2. As part of the validation context

You can also supply an array of `middleware` objects. The last middleware will be invoked first. The validation context middleware(s) are executed before the validator props middleware(s).

### CODE REVIEW

**Comment by jeffhandley** [comment]
@CrshOverride What do you think of this approach?

Here's a unit test that shows producing a `validationErrors` array: https://github.com/jeffhandley/strickland/pull/33/files#diff-4386d97b978986e7fe3328e4304dd158R505-R529

This is only implemented on `every` for sake of illustration, but the pattern would carry over to `all` and `objectProps` very similarly.

**Comment by CrshOverride** [comment]
@jeffhandley I definitely like it! I think this is definitely the "best of both worlds" approach. Let me know if there's anything I can help with (documentation, code, etc).

**Comment by jeffhandley** [comment]
Thanks, @CrshOverride!  I'd be happy for you to help out here a bit.  I could use your input on this design detail that I can't stop going back and forth on:

* While writing the unit tests for the `prepareResult` middleware, I kept wanting to just receive the default result (that has the validator result props and the validator props already spread), and then augment that result with an extra property.
* This approach actually makes that clumsy, because you have to call the `nextPrepare` function.
* This has led me to go back and forth on whether the middlewares should be executed "inside-out" or "outside-in" (first-to-last, or last-to-first).
* Right now, they're executing outside-in (last-to-first), and you can optionally interrupt the call chain.
* I could see the argument that inside-out (first-to-last) would be better in some cases though.
* With that approach, we would still need to use the `nextPrepare` argument, but at least augmenting the result wouldn't require you to call `nextPrepare`, grab its result, and then augment it -- you would just simply augment the provided result.
* So I think I'm leaning toward inside-out (first-to-last) middleware order being more natural.
* That would also change it such that validator prop middleware would be executed before validation context middleware, which (reflecting on it even more) also feels more natural/consistent
* **What do you think on the ordering?**
* **And do you think we should make the middleware chain interruptible** by providing the `nextPrepare` function as a parameter, or should we just always walk the whole list of middlewares?
* If we always walk the full chain, the simple middlewares would be easier to write, but no middleware could signal "stop calling middleware on this result"

If we did inside-out (first-to-last), uninterruptible middleware ordering, then the signatures would be:

``` js
const middleware = {
    reduceResults(accumulator, currentResult, { value, props, context, previousResult }) {
        // This behaves as a passthrough middleware
        // The core accumulation reducer will have already been called, so this gives an opportunity
        // to further augment the accumulated result. The `previousResult` object could be provided
        // optionally to allow a middleware to override any accumulation earlier middleware(s) and the
        // built-in accumulation would have already performed.       
        return accumulator;
    },
    prepareResult(result, { value, props, context, validatorResult }) {
        // This behaves as a passthrough middleware
        // The core result preparation would have already been called, as would earlier middleware(s).
        // So this is primarily an opportunity to augment the result. But the optional `validatorResult`
        // argument would be the raw result before any result preparation (built-in or earlier middleware(s))
        // so the middleware could choose to discard any preparation already performed.
        return result;
    }
};
```

**Comment by jeffhandley** [comment]
Also, @CrshOverride -- once we solidify the pattern and get the feature merged in, I'll gladly accept some help with updating the docs.  I suspect we'll want to add a new section to the "Composition" area.

**Comment by jeffhandley** [comment]
I created a pull request that illustrates the alternate approach as #34.

**Comment by jeffhandley** [comment]
Closing in favor of #39, per [this comment](https://github.com/jeffhandley/strickland/pull/34#issuecomment-656297600).

**Pull request closed without merging**
