### PR TITLE
WIP: aggregate validationResults and validationErrors for all/every/objectProps

### PR DESCRIPTION
**Pull request by jeffhandley**
Create `validationResults` and `validationErrors` props on aggregated validation results (in `all`, `every`, and `objectProps`), so that `form` doesn't need to be used to get to those shapes.

Given the following validation rules:

``` js
{
    name: required(),
    homeAddress: {
        street: required(),
        city: required(),
        state: [required(), length(2, 2)]
    },
    workAddress: {
        street: [
            required(),
            {
                number: required(),
                name: required()
            }
        ],
        city: required(),
        state: [required(), length(2, 2)]
    }
}
```

And the following data:

``` json
{
    "name": "",
    "homeAddress": {
        "street": "9303 Lyon Dr.",
        "city": "Hill Valley",
        "state": ""
    },
    "workAddress": {
        "street": {
            "number": "",
            "name": ""
        },
        "city": "",
        "state": "ST"
    }
}
```

The following validation result is produced:
<details>
<summary>Click to reveal</summary>
<p>

``` json
{
    "isValid": false,
    "objectProps": {
        "name": {
            "isValid": false,
            "required": true,
            "value": ""
        },
        "homeAddress": {
            "isValid": false,
            "objectProps": {
                "street": {
                    "isValid": true,
                    "required": true,
                    "value": "9303 Lyon Dr."
                },
                "city": {
                    "isValid": true,
                    "required": true,
                    "value": "Hill Valley"
                },
                "state": {
                    "isValid": false,
                    "every": [
                        {
                            "isValid": false,
                            "required": true,
                            "value": ""
                        }
                    ],
                    "validationResults": [
                        {
                            "isValid": false,
                            "required": true,
                            "value": ""
                        }
                    ],
                    "required": true,
                    "value": "",
                    "validationErrors": [
                        {
                            "isValid": false,
                            "required": true,
                            "value": ""
                        }
                    ]
                }
            },
            "validationResults": [
                {
                    "fieldName": "street",
                    "isValid": true,
                    "required": true,
                    "value": "9303 Lyon Dr."
                },
                {
                    "fieldName": "city",
                    "isValid": true,
                    "required": true,
                    "value": "Hill Valley"
                },
                {
                    "fieldName": "state",
                    "isValid": false,
                    "validationResults": [
                        {
                            "isValid": false,
                            "required": true,
                            "value": ""
                        }
                    ],
                    "required": true,
                    "value": "",
                    "validationErrors": [
                        {
                            "isValid": false,
                            "required": true,
                            "value": ""
                        }
                    ]
                }
            ],
            "validationErrors": [
                {
                    "fieldName": "state",
                    "isValid": false,
                    "validationResults": [
                        {
                            "isValid": false,
                            "required": true,
                            "value": ""
                        }
                    ],
                    "required": true,
                    "value": "",
                    "validationErrors": [
                        {
                            "isValid": false,
                            "required": true,
                            "value": ""
                        }
                    ]
                }
            ],
            "value": {
                "street": "9303 Lyon Dr.",
                "city": "Hill Valley",
                "state": ""
            }
        },
        "workAddress": {
            "isValid": false,
            "objectProps": {
                "street": {
                    "isValid": false,
                    "every": [
                        {
                            "isValid": true,
                            "required": true,
                            "value": {
                                "number": "",
                                "name": ""
                            }
                        },
                        {
                            "isValid": false,
                            "objectProps": {
                                "number": {
                                    "isValid": false,
                                    "required": true,
                                    "value": ""
                                },
                                "name": {
                                    "isValid": false,
                                    "required": true,
                                    "value": ""
                                }
                            },
                            "validationResults": [
                                {
                                    "fieldName": "number",
                                    "isValid": false,
                                    "required": true,
                                    "value": ""
                                },
                                {
                                    "fieldName": "name",
                                    "isValid": false,
                                    "required": true,
                                    "value": ""
                                }
                            ],
                            "validationErrors": [
                                {
                                    "fieldName": "number",
                                    "isValid": false,
                                    "required": true,
                                    "value": ""
                                },
                                {
                                    "fieldName": "name",
                                    "isValid": false,
                                    "required": true,
                                    "value": ""
                                }
                            ],
                            "value": {
                                "number": "",
                                "name": ""
                            }
                        }
                    ],
                    "validationResults": [
                        {
                            "isValid": true,
                            "required": true,
                            "value": {
                                "number": "",
                                "name": ""
                            }
                        },
                        {
                            "fieldName": "number",
                            "isValid": false,
                            "required": true,
                            "value": ""
                        },
                        {
                            "fieldName": "name",
                            "isValid": false,
                            "required": true,
                            "value": ""
                        }
                    ],
                    "required": true,
                    "value": {
                        "number": "",
                        "name": ""
                    },
                    "objectProps": {
                        "number": {
                            "isValid": false,
                            "required": true,
                            "value": ""
                        },
                        "name": {
                            "isValid": false,
                            "required": true,
                            "value": ""
                        }
                    },
                    "validationErrors": [
                        {
                            "fieldName": "number",
                            "isValid": false,
                            "required": true,
                            "value": ""
                        },
                        {
                            "fieldName": "name",
                            "isValid": false,
                            "required": true,
                            "value": ""
                        }
                    ]
                },
                "city": {
                    "isValid": false,
                    "required": true,
                    "value": ""
                },
                "state": {
                    "isValid": true,
                    "every": [
                        {
                            "isValid": true,
                            "required": true,
                            "value": "ST"
                        },
                        {
                            "minLength": 2,
                            "maxLength": 2,
                            "isValid": true,
                            "every": [
                                {
                                    "minLength": 2,
                                    "isValid": true,
                                    "length": 2,
                                    "value": "ST"
                                },
                                {
                                    "maxLength": 2,
                                    "isValid": true,
                                    "length": 2,
                                    "value": "ST"
                                }
                            ],
                            "validationResults": [
                                {
                                    "minLength": 2,
                                    "isValid": true,
                                    "length": 2,
                                    "value": "ST"
                                },
                                {
                                    "maxLength": 2,
                                    "isValid": true,
                                    "length": 2,
                                    "value": "ST"
                                }
                            ],
                            "length": 2,
                            "value": "ST",
                            "validationErrors": []
                        }
                    ],
                    "validationResults": [
                        {
                            "isValid": true,
                            "required": true,
                            "value": "ST"
                        },
                        {
                            "minLength": 2,
                            "isValid": true,
                            "length": 2,
                            "value": "ST"
                        },
                        {
                            "maxLength": 2,
                            "isValid": true,
                            "length": 2,
                            "value": "ST"
                        }
                    ],
                    "required": true,
                    "value": "ST",
                    "minLength": 2,
                    "maxLength": 2,
                    "length": 2,
                    "validationErrors": []
                }
            },
            "validationResults": [
                {
                    "fieldName": "street",
                    "isValid": false,
                    "validationResults": [
                        {
                            "isValid": true,
                            "required": true,
                            "value": {
                                "number": "",
                                "name": ""
                            }
                        },
                        {
                            "fieldName": "number",
                            "isValid": false,
                            "required": true,
                            "value": ""
                        },
                        {
                            "fieldName": "name",
                            "isValid": false,
                            "required": true,
                            "value": ""
                        }
                    ],
                    "required": true,
                    "value": {
                        "number": "",
                        "name": ""
                    },
                    "validationErrors": [
                        {
                            "fieldName": "number",
                            "isValid": false,
                            "required": true,
                            "value": ""
                        },
                        {
                            "fieldName": "name",
                            "isValid": false,
                            "required": true,
                            "value": ""
                        }
                    ]
                },
                {
                    "fieldName": "city",
                    "isValid": false,
                    "required": true,
                    "value": ""
                },
                {
                    "fieldName": "state",
                    "isValid": true,
                    "validationResults": [
                        {
                            "isValid": true,
                            "required": true,
                            "value": "ST"
                        },
                        {
                            "minLength": 2,
                            "isValid": true,
                            "length": 2,
                            "value": "ST"
                        },
                        {
                            "maxLength": 2,
                            "isValid": true,
                            "length": 2,
                            "value": "ST"
                        }
                    ],
                    "required": true,
                    "value": "ST",
                    "minLength": 2,
                    "maxLength": 2,
                    "length": 2,
                    "validationErrors": []
                }
            ],
            "validationErrors": [
                {
                    "fieldName": "street",
                    "isValid": false,
                    "validationResults": [
                        {
                            "isValid": true,
                            "required": true,
                            "value": {
                                "number": "",
                                "name": ""
                            }
                        },
                        {
                            "fieldName": "number",
                            "isValid": false,
                            "required": true,
                            "value": ""
                        },
                        {
                            "fieldName": "name",
                            "isValid": false,
                            "required": true,
                            "value": ""
                        }
                    ],
                    "required": true,
                    "value": {
                        "number": "",
                        "name": ""
                    },
                    "validationErrors": [
                        {
                            "fieldName": "number",
                            "isValid": false,
                            "required": true,
                            "value": ""
                        },
                        {
                            "fieldName": "name",
                            "isValid": false,
                            "required": true,
                            "value": ""
                        }
                    ]
                },
                {
                    "fieldName": "city",
                    "isValid": false,
                    "required": true,
                    "value": ""
                }
            ],
            "value": {
                "street": {
                    "number": "",
                    "name": ""
                },
                "city": "",
                "state": "ST"
            }
        }
    },
    "validationResults": [
        {
            "fieldName": "name",
            "isValid": false,
            "required": true,
            "value": ""
        },
        {
            "fieldName": "homeAddress",
            "isValid": false,
            "validationResults": [
                {
                    "fieldName": "street",
                    "isValid": true,
                    "required": true,
                    "value": "9303 Lyon Dr."
                },
                {
                    "fieldName": "city",
                    "isValid": true,
                    "required": true,
                    "value": "Hill Valley"
                },
                {
                    "fieldName": "state",
                    "isValid": false,
                    "validationResults": [
                        {
                            "isValid": false,
                            "required": true,
                            "value": ""
                        }
                    ],
                    "required": true,
                    "value": "",
                    "validationErrors": [
                        {
                            "isValid": false,
                            "required": true,
                            "value": ""
                        }
                    ]
                }
            ],
            "validationErrors": [
                {
                    "fieldName": "state",
                    "isValid": false,
                    "validationResults": [
                        {
                            "isValid": false,
                            "required": true,
                            "value": ""
                        }
                    ],
                    "required": true,
                    "value": "",
                    "validationErrors": [
                        {
                            "isValid": false,
                            "required": true,
                            "value": ""
                        }
                    ]
                }
            ],
            "value": {
                "street": "9303 Lyon Dr.",
                "city": "Hill Valley",
                "state": ""
            }
        },
        {
            "fieldName": "workAddress",
            "isValid": false,
            "validationResults": [
                {
                    "fieldName": "street",
                    "isValid": false,
                    "validationResults": [
                        {
                            "isValid": true,
                            "required": true,
                            "value": {
                                "number": "",
                                "name": ""
                            }
                        },
                        {
                            "fieldName": "number",
                            "isValid": false,
                            "required": true,
                            "value": ""
                        },
                        {
                            "fieldName": "name",
                            "isValid": false,
                            "required": true,
                            "value": ""
                        }
                    ],
                    "required": true,
                    "value": {
                        "number": "",
                        "name": ""
                    },
                    "validationErrors": [
                        {
                            "fieldName": "number",
                            "isValid": false,
                            "required": true,
                            "value": ""
                        },
                        {
                            "fieldName": "name",
                            "isValid": false,
                            "required": true,
                            "value": ""
                        }
                    ]
                },
                {
                    "fieldName": "city",
                    "isValid": false,
                    "required": true,
                    "value": ""
                },
                {
                    "fieldName": "state",
                    "isValid": true,
                    "validationResults": [
                        {
                            "isValid": true,
                            "required": true,
                            "value": "ST"
                        },
                        {
                            "minLength": 2,
                            "isValid": true,
                            "length": 2,
                            "value": "ST"
                        },
                        {
                            "maxLength": 2,
                            "isValid": true,
                            "length": 2,
                            "value": "ST"
                        }
                    ],
                    "required": true,
                    "value": "ST",
                    "minLength": 2,
                    "maxLength": 2,
                    "length": 2,
                    "validationErrors": []
                }
            ],
            "validationErrors": [
                {
                    "fieldName": "street",
                    "isValid": false,
                    "validationResults": [
                        {
                            "isValid": true,
                            "required": true,
                            "value": {
                                "number": "",
                                "name": ""
                            }
                        },
                        {
                            "fieldName": "number",
                            "isValid": false,
                            "required": true,
                            "value": ""
                        },
                        {
                            "fieldName": "name",
                            "isValid": false,
                            "required": true,
                            "value": ""
                        }
                    ],
                    "required": true,
                    "value": {
                        "number": "",
                        "name": ""
                    },
                    "validationErrors": [
                        {
                            "fieldName": "number",
                            "isValid": false,
                            "required": true,
                            "value": ""
                        },
                        {
                            "fieldName": "name",
                            "isValid": false,
                            "required": true,
                            "value": ""
                        }
                    ]
                },
                {
                    "fieldName": "city",
                    "isValid": false,
                    "required": true,
                    "value": ""
                }
            ],
            "value": {
                "street": {
                    "number": "",
                    "name": ""
                },
                "city": "",
                "state": "ST"
            }
        }
    ],
    "validationErrors": [
        {
            "fieldName": "name",
            "isValid": false,
            "required": true,
            "value": ""
        },
        {
            "fieldName": "homeAddress",
            "isValid": false,
            "validationResults": [
                {
                    "fieldName": "street",
                    "isValid": true,
                    "required": true,
                    "value": "9303 Lyon Dr."
                },
                {
                    "fieldName": "city",
                    "isValid": true,
                    "required": true,
                    "value": "Hill Valley"
                },
                {
                    "fieldName": "state",
                    "isValid": false,
                    "validationResults": [
                        {
                            "isValid": false,
                            "required": true,
                            "value": ""
                        }
                    ],
                    "required": true,
                    "value": "",
                    "validationErrors": [
                        {
                            "isValid": false,
                            "required": true,
                            "value": ""
                        }
                    ]
                }
            ],
            "validationErrors": [
                {
                    "fieldName": "state",
                    "isValid": false,
                    "validationResults": [
                        {
                            "isValid": false,
                            "required": true,
                            "value": ""
                        }
                    ],
                    "required": true,
                    "value": "",
                    "validationErrors": [
                        {
                            "isValid": false,
                            "required": true,
                            "value": ""
                        }
                    ]
                }
            ],
            "value": {
                "street": "9303 Lyon Dr.",
                "city": "Hill Valley",
                "state": ""
            }
        },
        {
            "fieldName": "workAddress",
            "isValid": false,
            "validationResults": [
                {
                    "fieldName": "street",
                    "isValid": false,
                    "validationResults": [
                        {
                            "isValid": true,
                            "required": true,
                            "value": {
                                "number": "",
                                "name": ""
                            }
                        },
                        {
                            "fieldName": "number",
                            "isValid": false,
                            "required": true,
                            "value": ""
                        },
                        {
                            "fieldName": "name",
                            "isValid": false,
                            "required": true,
                            "value": ""
                        }
                    ],
                    "required": true,
                    "value": {
                        "number": "",
                        "name": ""
                    },
                    "validationErrors": [
                        {
                            "fieldName": "number",
                            "isValid": false,
                            "required": true,
                            "value": ""
                        },
                        {
                            "fieldName": "name",
                            "isValid": false,
                            "required": true,
                            "value": ""
                        }
                    ]
                },
                {
                    "fieldName": "city",
                    "isValid": false,
                    "required": true,
                    "value": ""
                },
                {
                    "fieldName": "state",
                    "isValid": true,
                    "validationResults": [
                        {
                            "isValid": true,
                            "required": true,
                            "value": "ST"
                        },
                        {
                            "minLength": 2,
                            "isValid": true,
                            "length": 2,
                            "value": "ST"
                        },
                        {
                            "maxLength": 2,
                            "isValid": true,
                            "length": 2,
                            "value": "ST"
                        }
                    ],
                    "required": true,
                    "value": "ST",
                    "minLength": 2,
                    "maxLength": 2,
                    "length": 2,
                    "validationErrors": []
                }
            ],
            "validationErrors": [
                {
                    "fieldName": "street",
                    "isValid": false,
                    "validationResults": [
                        {
                            "isValid": true,
                            "required": true,
                            "value": {
                                "number": "",
                                "name": ""
                            }
                        },
                        {
                            "fieldName": "number",
                            "isValid": false,
                            "required": true,
                            "value": ""
                        },
                        {
                            "fieldName": "name",
                            "isValid": false,
                            "required": true,
                            "value": ""
                        }
                    ],
                    "required": true,
                    "value": {
                        "number": "",
                        "name": ""
                    },
                    "validationErrors": [
                        {
                            "fieldName": "number",
                            "isValid": false,
                            "required": true,
                            "value": ""
                        },
                        {
                            "fieldName": "name",
                            "isValid": false,
                            "required": true,
                            "value": ""
                        }
                    ]
                },
                {
                    "fieldName": "city",
                    "isValid": false,
                    "required": true,
                    "value": ""
                }
            ],
            "value": {
                "street": {
                    "number": "",
                    "name": ""
                },
                "city": "",
                "state": "ST"
            }
        }
    ]
}
```

</p>
</details>

This feature was previously omitted because of the verbosity in the result that is incurred--and there's a lot of duplication of data as well.  I'd love suggestions on if/how the verbosity and duplication could be reduced.

I was tempted to omit the `all`, `every`, and `objectProps` properties on the results, replacing them with `validationResults`, but they do offer different shapes that can be convenient in some scenarios.

I was also temped to use a `validationContext` switch to enable `validationResults` and `validationErrors` in the result, but with the convention of invoking `every` and `objectProps` by simply defining an array, passing context to those validators is cumbersome in some scenarios--it would likely be passed into the `validate()` method and passed through.

I was also originally planning to create a `getValidationErrors()` utility function, but some data fidelity is harder to maintain with that approach, as it would need to walk the object graph looking for `all`, `every`, and `objectProps` on each node of the results--plus, validators can add objects and arrays to results, which adds risk to trying to walk the object graph again. This led me to conclude that producing the `validationResults` and `validationErrors` during validation is safest.

Still needed:

* [ ] Docs updates
* [ ] Unit tests related to async validators
* [ ] Unit tests with nested `all` and `every` validators

### CODE REVIEW

**Comment by jeffhandley** [comment]
I'm hoping @CrshOverride, @benmccallum, and @casche can all take a look at this.

**Comment by jeffhandley** [comment]
To capture the effects this has on the `form` validator (where the bloat and duplication in the results is even more pronounced), here's a snapshot of a before/after for a set of `form` results.

**Before this PR**
``` js
{
    "isValid": false,
    "value": {
        "firstName": "Marty",
        "lastName": "McFly",
        "username": "",
        "password": "marty88",
        "comparePassword": "einstein"
    },
    "form": {
        "isComplete": true,
        "validationResults": {
            "firstName": {
                "isValid": true,
                "required": true,
                "value": "Marty"
            },
            "lastName": {
                "isValid": true,
                "required": true,
                "value": "McFly"
            },
            "username": {
                "isValid": false,
                "required": true,
                "value": ""
            },
            "password": {
                "isValid": true,
                "every": [
                    {
                        "isValid": true,
                        "required": true,
                        "value": "marty88"
                    },
                    {
                        "minLength": 6,
                        "isValid": true,
                        "length": 7,
                        "value": "marty88"
                    }
                ],
                "required": true,
                "value": "marty88",
                "minLength": 6,
                "length": 7
            },
            "comparePassword": {
                "isValid": false,
                "every": [
                    {
                        "isValid": true,
                        "required": true,
                        "value": "einstein"
                    },
                    {
                        "compare": "marty88",
                        "isValid": false,
                        "value": "einstein"
                    }
                ],
                "required": true,
                "value": "einstein",
                "compare": "marty88"
            }
        },
        "validationErrors": [
            {
                "fieldName": "username",
                "isValid": false,
                "required": true,
                "value": ""
            },
            {
                "fieldName": "comparePassword",
                "isValid": false,
                "every": [
                    {
                        "isValid": true,
                        "required": true,
                        "value": "einstein"
                    },
                    {
                        "compare": "marty88",
                        "isValid": false,
                        "value": "einstein"
                    }
                ],
                "required": true,
                "value": "einstein",
                "compare": "marty88"
            }
        ]
    }
}
```

**After**
``` js
{
    "isValid": false,
    "validationResults": [
        {
            "fieldName": "firstName",
            "isValid": true,
            "required": true,
            "value": "Marty"
        },
        {
            "fieldName": "lastName",
            "isValid": true,
            "required": true,
            "value": "McFly"
        },
        {
            "fieldName": "username",
            "isValid": false,
            "required": true,
            "value": ""
        },
        {
            "fieldName": "password",
            "isValid": true,
            "every": [
                {
                    "isValid": true,
                    "required": true,
                    "value": "marty88"
                },
                {
                    "minLength": 6,
                    "isValid": true,
                    "length": 7,
                    "value": "marty88"
                }
            ],
            "validationResults": [
                {
                    "isValid": true,
                    "required": true,
                    "value": "marty88"
                },
                {
                    "minLength": 6,
                    "isValid": true,
                    "length": 7,
                    "value": "marty88"
                }
            ],
            "required": true,
            "value": "marty88",
            "minLength": 6,
            "length": 7,
            "validationErrors": []
        },
        {
            "fieldName": "comparePassword",
            "isValid": false,
            "every": [
                {
                    "isValid": true,
                    "required": true,
                    "value": "einstein"
                },
                {
                    "compare": "marty88",
                    "isValid": false,
                    "value": "einstein"
                }
            ],
            "validationResults": [
                {
                    "isValid": true,
                    "required": true,
                    "value": "einstein"
                },
                {
                    "compare": "marty88",
                    "isValid": false,
                    "value": "einstein"
                }
            ],
            "required": true,
            "value": "einstein",
            "compare": "marty88",
            "validationErrors": [
                {
                    "compare": "marty88",
                    "isValid": false,
                    "value": "einstein"
                }
            ]
        }
    ],
    "validationErrors": [
        {
            "fieldName": "username",
            "isValid": false,
            "required": true,
            "value": ""
        },
        {
            "fieldName": "comparePassword",
            "isValid": false,
            "every": [
                {
                    "isValid": true,
                    "required": true,
                    "value": "einstein"
                },
                {
                    "compare": "marty88",
                    "isValid": false,
                    "value": "einstein"
                }
            ],
            "validationResults": [
                {
                    "isValid": true,
                    "required": true,
                    "value": "einstein"
                },
                {
                    "compare": "marty88",
                    "isValid": false,
                    "value": "einstein"
                }
            ],
            "required": true,
            "value": "einstein",
            "compare": "marty88",
            "validationErrors": [
                {
                    "compare": "marty88",
                    "isValid": false,
                    "value": "einstein"
                }
            ]
        }
    ],
    "value": {
        "firstName": "Marty",
        "lastName": "McFly",
        "username": "",
        "password": "marty88",
        "comparePassword": "einstein"
    },
    "form": {
        "isComplete": true,
        "validationResults": {
            "firstName": {
                "isValid": true,
                "required": true,
                "value": "Marty"
            },
            "lastName": {
                "isValid": true,
                "required": true,
                "value": "McFly"
            },
            "username": {
                "isValid": false,
                "required": true,
                "value": ""
            },
            "password": {
                "isValid": true,
                "every": [
                    {
                        "isValid": true,
                        "required": true,
                        "value": "marty88"
                    },
                    {
                        "minLength": 6,
                        "isValid": true,
                        "length": 7,
                        "value": "marty88"
                    }
                ],
                "validationResults": [
                    {
                        "isValid": true,
                        "required": true,
                        "value": "marty88"
                    },
                    {
                        "minLength": 6,
                        "isValid": true,
                        "length": 7,
                        "value": "marty88"
                    }
                ],
                "required": true,
                "value": "marty88",
                "minLength": 6,
                "length": 7,
                "validationErrors": []
            },
            "comparePassword": {
                "isValid": false,
                "every": [
                    {
                        "isValid": true,
                        "required": true,
                        "value": "einstein"
                    },
                    {
                        "compare": "marty88",
                        "isValid": false,
                        "value": "einstein"
                    }
                ],
                "validationResults": [
                    {
                        "isValid": true,
                        "required": true,
                        "value": "einstein"
                    },
                    {
                        "compare": "marty88",
                        "isValid": false,
                        "value": "einstein"
                    }
                ],
                "required": true,
                "value": "einstein",
                "compare": "marty88",
                "validationErrors": [
                    {
                        "compare": "marty88",
                        "isValid": false,
                        "value": "einstein"
                    }
                ]
            }
        },
        "validationErrors": [
            {
                "fieldName": "username",
                "isValid": false,
                "required": true,
                "value": ""
            },
            {
                "fieldName": "comparePassword",
                "isValid": false,
                "every": [
                    {
                        "isValid": true,
                        "required": true,
                        "value": "einstein"
                    },
                    {
                        "compare": "marty88",
                        "isValid": false,
                        "value": "einstein"
                    }
                ],
                "validationResults": [
                    {
                        "isValid": true,
                        "required": true,
                        "value": "einstein"
                    },
                    {
                        "compare": "marty88",
                        "isValid": false,
                        "value": "einstein"
                    }
                ],
                "required": true,
                "value": "einstein",
                "compare": "marty88",
                "validationErrors": [
                    {
                        "compare": "marty88",
                        "isValid": false,
                        "value": "einstein"
                    }
                ]
            }
        ]
    }
}
```

**Comment by CrshOverride** [comment]
@jeffhandley Rather than modify the existing results, would it make more sense to have something that could wrap `objectProps`, `every`, `all`, etc. and return the validation errors (and allow for the flatting context)`?

Something like:

```js
let validator = emitValidationErrors(objectProps({}));
let result = validate(validator, {});
```

I think that would give you the context that you need for building the results rather than relying on a function that transforms the results after `validate` runs.

**Comment by jeffhandley** [comment]
@CrshOverride Neat idea -- essentially a set of higher-order functions that can wrap a composite validator.

The challenge trying to do this as wrapper functions is that there's context within the composite validators (`all`, `every`, `objectProps`, and `form`) that is lost once the results are returned. Trying to reverse-engineer that context wouldn't offer the needed fidelity. _But_ with your idea, maybe we can tap into a pattern that organically emerged in those validators...

Each of those validators has an internal pattern of 2 methods involved in composing and returning the results:

* `applyNextResult(previousResult, nextResult)`
    * This is a reducer function that builds up the composite result as new results are accumulated
    * `all`, `every`, and `objectProps` all have their specific higher-order logic in these functions
    * In this PR, `all`, and `every` use this hook to accumulate results into the `validationResults` array
    * `form` inherits the behavior of `objectProps` since `form` is actually just a higher-order validator over `objectProps`
* `prepareResult(props, result)`
    * This is where the result can be augmented (or transformed) before it's returned
    * In this PR, `all` and `every` use this to add the `validationErrors`, which is just a filter over `validationResults`
    * In this PR, `objectProps` uses this to transform the result to include `validationResult` as well as to then filter that into `validationErrors`
    * `form` also uses this to manage state including handling of async validation

I hadn't realized that `form` is already acting has a high-order validator, but it is.  Perhaps that concept of higher-order validators can be formalized.  And I'm wondering if creating a middleware pattern would be the way to do it.  Middleware could allow:

* All built-in validators to support a `prepareResult` middleware hook
* Composite validators to also support an `applyNextResult` middleware hook (maybe even naming it `reduceResults` since it's used as a reducer)
* The concept of higher-order validators would get formalized such that a higher-order validator's purpose is to provide middleware into the wrapped validator
* When there are nested higher-order validators, the middleware _would not_ propagate inward automatically -- so applying middleware at the outermost layer would not influence the `prepareResult` and `reduceResults` steps for inner validation -- this would address the issue shown in the results above that `validationResults` and `validationErrors` get applied at every single level of `all`, `every`, and `objectProps` validation

It could look similar to what you've shown:

**Using Validator Props to Provide Middleware**
Using Validator Props, the middleware **would not** get applied to nested validators.  This would produce a result similar to what `form` can do today, where only the outer object has the `validationResults` and `validationErrors` props.

``` js
// aggregate all results into the validationResults array
let reduceResults = (applyResult, previousResult, nextResult, context) => applyResult({
    ...previousResult,
    validationResults: [
        ...previousResult.validationResults,
        nextResult
    ]
});

// produce a filtered array of validationErrors
let prepareResult = (returnResult, props, result, value, context) => returnResult({
    ...result,
    validationErrors: result.validationResults.filter(({isValid}) => !isValid)
});

let validator = objectProps(
    { /* object validators */ },
    { middleware: { reduceResults, prepareResult } }
);

let result = validate(validator, {});
```

**Using Validation Context to Provide Middleware**
Using Validator Context, the middleware **would** get applied to nested validators.  This could produce a result similar to what this WIP illustrated above, where every level of nested objects has `validationResults` and `validationErrors` props.

``` js
let validator = { /* object validators */ }; // using the objectProps convention

let result = validate(validator, {}, { middleware: { reduceResults, prepareResult } });
```

I want to spend more time thinking about what an `applyMiddleware` style approach could look like for this to materialize in higher-order validators though.  I've had several false starts writing up what that usage could look like, but I can't get it quite right.  I'm trying to draw inspiration from `redux`'s middleware approach. But I think the Validation Props and Validation Context inner working would be there, for `all`, `every`, and `objectProps` to respect those middlewares and with `form` using the Validation Props over `objectProps` to gain its functionality.

**Comment by benmccallum** [comment]
Sorry @jeffhandley, I'd only looked at this on my phone and completely missed the outstanding input you needed. 

I wouldn't consider the bloat a problem, it's not going to be detrimental. 

The discussion around how this actually built up though is really interesting and I think you guys are 100% on the right track. + middleware is never a bad idea :P It's proving extremely useful in HotChocolate right now (a dotnet GraphQL fx).

**Comment by benmccallum** [comment]
Sorry I can't add more to the discussion, pretty slammed at the moment, but I did take a few mins to put your large code blocks into collapsible sections so that it's easier to peruse

**Comment by jeffhandley** [comment]
Thanks, @benmccallum and @CrshOverride!

I'm spiking out a middleware-based approach instead of what this PR had captured, so I'm going to close this PR.  I appreciate the help here.

**Pull request closed without merging**
