### PR TITLE
WIP: Add middleware support to the every validator (alternate approach)

### PR DESCRIPTION
**Pull request by jeffhandley**
This illustrates what a middleware contract could look like for the `every` validator to support `reduceResults` and `prepareResult` middleware, that can augment or override the default behavior of how results are aggregated and returned.

The contract for middleware is:

``` js
const middleware = {
    reduceResults(accumulator, currentResult, { value, props, context, previousResult }) {
        // This behaves as a passthrough middleware
        // The core accumulation reducer will have already been called, so this gives an opportunity
        // to further augment the accumulated result. The `previousResult` object could be provided
        // optionally to allow a middleware to override any accumulation earlier middleware(s) and the
        // built-in accumulation would have already performed.       
        return accumulator;
    },
    prepareResult(result, { value, props, context, validatorResult }) {
        // This behaves as a passthrough middleware
        // The core result preparation would have already been called, as would earlier middleware(s).
        // So this is primarily an opportunity to augment the result. But the optional `validatorResult`
        // argument would be the raw result before any result preparation (built-in or earlier middleware(s))
        // so the middleware could choose to discard any preparation already performed.
        return result;
    }
};
```

This `middleware` can be supplied either as a single object with those functions, or as an array of middleware objects with those functions, and it can be supplied either on validator props or on validation context. The middleware will be invoked in this order:

1. The default behavior provided by the `every` validator
2. The list of middlewares provided as validator props, in order
3. The list of middlewares provided on the validation context, in order

This is an alternate approach to #33.

### CODE REVIEW

**Comment by jeffhandley** [comment]
@CrshOverride With https://github.com/jeffhandley/strickland/pull/34/commits/9175af30c02e278ebc666ae39b4011cc7347c1f5, there's now a `withMiddleware` function that very closely matches your original request.  I couldn't see how to pull this off until I finished adding middleware support to the `all`, `every`, `some`, and `objectProps` validators, but then it became pretty clear (and easy) to add `withMiddleware` support for all of those.

Here's an example from a unit test:

``` js
const addFromPrepareResult = (result) => ({
    ...result,
    fromPrepareResult: (result.fromPrepareResult || 0) + 1
});

const addFromReduceResults = (accumulator, currentResult) => ({
    fromReduceResults: (accumulator.fromReduceResults || 0) + 1
});

const middleware = {
    prepareResult: addFromPrepareResult,
    reduceResults: addFromReduceResults
};

const validate = objectProps({name: required()}, {prop: 'propValue'});

// Wrap in middleware twice for nested levels of middleware
const validateWithMiddleware = withMiddleware(withMiddleware(validate, middleware), middleware);

const result = validateWithMiddleware({});

expect(result).toMatchObject({
    fromPrepareResult: 2,
    fromReduceResults: 2
});
```

But existing conventions work with it too, so you can just supply the `objectProps` validation object or an array of validators for `every`:

``` js
const validate = withMiddleware({
    name: withMiddleware([required(), minLength(2)], nameValidatorMiddleware)
}, objectValidatorMiddleware);
```

With middleware being supplied through validation context, and with the support for middleware to be an array of middleware objects, the `withMiddleware` function is actually pretty straightforward:

``` js
import validate from './validate';

export default (validator, middleware) => (value, validationContext) =>
    validate(validator, value, {
        ...validationContext,
        middleware: validationContext && validationContext.middleware ? [
            ...(Array.isArray(middleware) ? middleware : [middleware]),
            ...(Array.isArray(validationContext.middleware) ?
                    validationContext.middleware :
                    [validationContext.middleware]
                )
        ] : middleware
    });
```

This makes it relatively trivial to create and use middleware for adding `validationErrors` to either `every` or `objectProps` validators.  (In fact, there are unit tests asserting the scenario).  From there, I think a `withValidationErrors` function would look roughly like this:

``` js
const prepareResultWithValidationErrorsForEvery (result) => ({
    ...result,
    validationErrors: result.every.filter(({isValid}) => !isValid)
});

const prepareResultWithValidationErrorsForObjectProps = (result) => ({
    ...result,
    validationErrors: Object.keys(result.objectProps)
        .map((propName) => result.objectProps[propName])
        .filter(({isValid}) => !isValid)
});

const prepareResultWithValidationErrors = (result) => {
    if (result.objectProps) {
        return prepareResultWithValidationErrorsForEvery(result);
    } else if (result.every) {
        return prepareResultWithValidationErrorsForObjectProps(result);
    }
    
    return result;
};

const middleware = {
    prepareResult: prepareResultWithValidationErrors
};

const withValidationErrors(validator) => withMiddleware(validator, {middleware});
```

I'm hoping that's pretty close to what you had originally imagined a `withValidationErrors` wrapper could look like.

I'm now considering the following points...

* Middleware is currently supported (in this PR) on both validation context and validator props
* `withMiddleware` makes it easy to wrap around any validator to provide context specific to that validator (and not the whole graph of validation)
* Middleware should be excluded from the validation result props (they are with this PR anyway)
* Excluding middleware from props required a little clumsiness
* That clumsiness is making me pause at adding middleware support to all validators (because then custom validators would need to have the same clumsiness)

...I'm considering the following changes to this PR:

1. Middleware support would be _removed_ from validator props
1. Middleware would therefore only be supported on validation context
1. A new `withContext` function would be introduced, working similarly to `withMiddleware`, but allowing any validator to be wrapped such that validation context could be provided to that validator (and its descendants)
1. The `withMiddleware` function would be refactored to use `withContext` under the covers
1. All built-in validators would gain support for the `prepareResult` middleware

**Comment by jeffhandley** [comment]
I realized a significant limitation to `withValidationErrors` as illustrated above.  I was actually considering that the way `withValidationErrors` is written above, perhaps the middleware approach was overkill and not even needed, as the following code would pull off `withValidationErrors` without even using middleware at all (only supporting the `every` validator in the illustration):

``` js
function withValidationErrors(validator) {
    return function validateWithValidationErrors(value, validationContext) {
        const result = validate(validator, value, validationContext);

        return {
            ...result,
            validationErrors: result.every.filter(({isValid}) => !isValid);
        };
    }
}
```

But, there's an important reason why the `prepareResult` middleware hook has value over this approach: **async validators**.  With the simple wrapper like the one here, only synchronous validation results would run gain the `validationErrors` result prop.  To handle async validation, the `validateWithValidationErrors` function in this illustration would also have to check to see if the result has a `validateAsync` function on its result, and wrap it in a `.then` call that augments the result with the `validationErrors` prop.  All of that plumbing is currently handled in this PR through the `prepareResult` middleware hook.

Alternatively to middleware though, we could still consider a function that wraps a validator like what is shown above, with the purpose of augmenting/transforming the result, and that function could take care of the async handling similar to how the middleware hooks do in this PR.

I'm going back and forth, unconvinced middleware is worth it.

**Comment by CrshOverride** [comment]
@jeffhandley If the middleware approach doesn't add significant complexity and adds the flexibility to handle async validators with more clarity than trying to sniff for promises on validators, I'd say that's reason enough alone to keep the middleware approach.

**Comment by jeffhandley** [comment]
Here's my current thinking:

1. Adding this middleware support into `all`, `every`, `some`, and `objectProps` was only _mildly_ invasive into those validators
2. Adding it into _all_ built-in validators would be _moderately_ invasive relative to the amount of code in those validators that would be related to middleware vs. the existing code
3. At the very least, all composite validators should support it, which would mean adding it to the new `arrayElements` validator, and probably the `form` validator too
4. To truly have middleware support throughout Strickland would mean prescribing that all validators support middleware, which would violate [design goal](https://www.strickland.io/design-goals) 6 ("Enable consumers to easily create their own validators")
5. The approach in #39 has zero invasiveness and unlocks many of the same scenarios while supporting scenarios of formatting results from any validator (all built-in validators as well as custom validators)

I know you initially suggested something closer to #39, @CrshOverride, and I just couldn't see how to achieve it at first, but I've dispelled my own previous thoughts that context about the results is lost once the validator lets go of the result.

I'm going to close this PR as well as #33, and pursue #39. I have some additional thoughts on that approach that could make it even richer too.

Thanks for reviewing and helping me work through this!

**Pull request closed without merging**
